# Prerequisites:
# 1) /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# 2) brew install ansible
# 3) ansible-galaxy install geerlingguy.mas
# 4) brew cask
# 5) brew tap buo/cask-upgrade
# 6) Launch like this ansible-playbook macosx.yml


- hosts: localhost
  gather_facts: false

  tasks:

    - name: Install Libs
      homebrew: name={{ item }} state=present
      with_items:
 #       - fish
        - pyenv
        - mas

    - name: Install Utilities
      homebrew_cask: name={{ item }} state=present
      with_items:
        - android-file-transfer
        - authy
        - avast-security
        - bitbar
        - coconutbattery
        - docker
        - etcher
        - flux
        - google-backup-and-sync
        - google-earth
        - imageoptim
        - lulu
        - quicklook-csv 
        - quicklook-json 
        - rsyncosx
        - smcfancontrol
        - spectacle
        - superduper
        - teamviewer
        - virtualbox
  #      - homebrew/cask-drivers/lg-onscreen-control
  #      - digikam
  #      - bootchamp
  #      - zerotier-one

    - name: Install Browsers
      homebrew_cask: name={{ item }} state=present
      with_items:
        - opera
        - google-chrome
        - firefox 

    - name: Install Dev Tools
      homebrew_cask: name={{ item }} state=present
      with_items:
        - visual-studio-code
#        - iterm2
        - terminus
        - sequel-pro 
        - sourcetree
        - github

    - name: Install Media App
      homebrew_cask: name={{ item }} state=present
      with_items:
        - calibre
        - vlc
        - deezer

    - name: Install Social Tools
      homebrew_cask: name={{ item }} state=present
      with_items:
        - skype

  
- hosts: localhost
  vars:
    mas_installed_apps:
      - { id: 425264550, name: "Blackmagic Disk Speed Test" }
      - { id: 411643860, name: "Daisy Disk" }
      - { id: 937984704, name: "Amphetamine" }
      - { id: 472226235, name: "Lanscan" }
      - { id: 926036361, name: "Lastpass" }
      - { id: 425424353, name: "The Unarchiver" }
      - { id: 497799835, name: "Xcode" }
      - { id: 523620159, name: "Clean My Drive" }
      - { id: 490461369, name: "Bandwidth+" }
      - { id: 921923693, name: "LibreOffice Vanilla" }
      
  roles:
    - geerlingguy.mas

  
  # To install manually: ring, RsyncOSXsched, davinci resolve



        
