
- hosts: localhost
  gather_facts: false

  tasks:
    - homebrew_cask:
        name: alfred
        state: present
    - homebrew_cask:
        name: visual-studio-code
        state: present
    - homebrew_cask:
        name: spectacle
        state: present        
    - homebrew_cask:
        name: google-chrome
        state: present
    - homebrew_cask:
        name: google-backup-and-sync
        state: present
    - homebrew_cask:
        name: android-file-transfer
        state: present
    - homebrew_cask:
        name: calibre
        state: present